// Isolated application state and browser profiles; no real chats or preferences.
import { chromium, expect } from '@playwright/test';
import { mkdtemp, mkdir, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { createService } from '../server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
await mkdir(path.join(root, '.cache'), { recursive: true });
const repo = await mkdtemp(path.join(root, '.cache/theme-ui-'));
await mkdir(path.join(repo, 'workspace/test'), { recursive: true });
await mkdir(path.join(repo, 'knowledge'), { recursive: true });
await cp(path.join(root, 'public/assets'), path.join(root, 'dist/assets'), { recursive: true });
await writeFile(path.join(repo, 'knowledge/notes.md'), '# Theme notes\n\nReadable **Markdown**.\n');
await writeFile(path.join(repo, 'workspace/test/report.html'), `<!doctype html><html data-mak-report="document"><head><style>body{background:#101115;color:#d3d0d9;min-height:2200px}h1{color:#fff}img{width:60px}</style></head><body><h1>Reading report</h1><p>Dark text on a light background.</p><input aria-label="Keep my draft" value="Original"><img alt="Artwork" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40'%3E%3Crect width='40' height='40' fill='%23ee3377'/%3E%3C/svg%3E"><script>window.mountId=crypto.randomUUID()</script></body></html>`);
await writeFile(path.join(repo, 'workspace/test/custom.html'), '<!doctype html><html data-mak-report="document" data-mak-theme="custom"><head><style>body{background:rgb(20,30,40);color:white}</style></head><body><h1>Custom game</h1><canvas style="background:rgb(30,80,40)"></canvas></body></html>');
await writeFile(path.join(repo, 'workspace/test/notes.md'), '# Readable notes\n\nA **strong** paragraph and [a link](https://example.com/).\n\n| Name | State |\n| --- | --- |\n| Theme | Ready |\n');
await writeFile(path.join(repo, 'workspace/workspace.json'), JSON.stringify({ entities: [{ id: 'test', folder: 'test', title: 'Theme check', sample: true, category: 'dev', created: '2026-10-02', status: 'active', defaultStep: 0, steps: [{ name: 'Report', path: 'report.html' }, { name: 'Notes', path: 'notes.md' }, { name: 'Custom game', path: 'custom.html' }] }] }));
let service, browser;
try {
  service = await createService({ repo, uiDir: path.join(root, 'dist') });
  browser = await chromium.launch({ channel: process.env.MRMAK_TEST_BROWSER || 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1300, height: 920 }, colorScheme: 'dark' });
  const page = await context.newPage(), second = await context.newPage(), chats = await context.newPage();
  const errors = []; for (const view of [page, second, chats]) { view.setDefaultTimeout(12000); view.on('pageerror', error => errors.push(error.message)); }
  await page.goto(service.urls.workspace + '#/test/0');
  await second.goto(service.urls.workspace);
  await chats.goto(service.urls.chats);
  await page.locator('.report-document[aria-busy=false]').waitFor();
  const report = () => page.frameLocator('iframe.report-frame');
  await expect(page.locator('html')).toHaveAttribute('data-workspace-theme', 'dark');
  const mountId = await report().locator('html').evaluate(() => window.mountId);
  await report().getByRole('textbox', { name: 'Keep my draft' }).fill('Keep this edit');
  await report().locator('body').evaluate(() => scrollTo(0, 400));
  await page.getByRole('button', { name: 'Toggle settings', exact: true }).click();
  await page.getByLabel('Workspace theme', { exact: true }).selectOption('light');
  await expect(page.locator('html')).toHaveAttribute('data-workspace-theme', 'light');
  await expect(second.locator('html')).toHaveAttribute('data-workspace-theme', 'light');
  await expect(second.locator('.content')).toHaveCSS('background-color', 'rgb(247, 248, 250)');
  await expect(second.locator('.entity-card')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  await expect(chats.locator('html')).toHaveAttribute('data-workspace-theme', 'dark');
  await expect(report().locator('html')).toHaveAttribute('data-mrmak-theme', 'light');
  assert.equal(await report().locator('body').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(255, 255, 255)');
  assert.equal(await report().locator('h1').evaluate(node => getComputedStyle(node).color), 'rgb(17, 21, 33)');
  assert.equal(await report().locator('html').evaluate(() => window.mountId), mountId);
  assert.equal(await report().locator('html').evaluate(() => scrollY), 400);
  assert.equal(await report().getByRole('textbox', { name: 'Keep my draft' }).inputValue(), 'Keep this edit');
  assert.equal(await report().getByRole('img', { name: 'Artwork' }).evaluate(node => getComputedStyle(node).filter), 'none');
  // Untrusted siblings and invalid values cannot change the report's theme.
  await report().locator('html').evaluate(() => window.dispatchEvent(new MessageEvent('message', { source: window, origin: location.origin, data: { type: 'mrmak:theme', theme: 'dark' } })));
  await expect(report().locator('html')).toHaveAttribute('data-mrmak-theme', 'light');
  const saved = await (await fetch(service.origin + '/api/settings', { method: 'POST', headers: { Authorization: `Bearer ${service.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ workspaceTheme: 'invalid' }) })).json();
  assert.equal(saved.workspaceTheme, 'light');
  await page.getByRole('button', { name: 'Close settings', exact: true }).click();
  await page.getByRole('tab', { name: 'Notes', exact: true }).click();
  await page.locator('.mak-markdown h1').waitFor();
  assert.equal(await page.locator('.mak-markdown h1').evaluate(node => getComputedStyle(node).color), 'rgb(17, 21, 33)');
  await page.getByRole('button', { name: 'Toggle files', exact: true }).click();
  await page.getByRole('treeitem', { name: /^knowledge$/ }).click();
  await page.getByRole('treeitem', { name: /^notes.md/ }).click();
  await page.getByRole('heading', { name: 'Theme notes', exact: true }).waitFor();
  await page.locator('.file-preview').getByRole('button', { name: 'Edit', exact: true }).click();
  assert.equal(await page.locator('.markdown-editor').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(255, 255, 255)');
  await page.getByRole('button', { name: 'Close file preview', exact: true }).click();
  await page.getByRole('button', { name: 'Toggle settings', exact: true }).click();
  await page.getByLabel('Workspace theme', { exact: true }).selectOption('system');
  await expect(page.locator('html')).toHaveAttribute('data-workspace-theme', 'dark');
  await page.emulateMedia({ colorScheme: 'light' });
  await expect(page.locator('html')).toHaveAttribute('data-workspace-theme', 'light');
  await page.getByLabel('Workspace theme', { exact: true }).selectOption('light');
  await page.getByRole('button', { name: 'Close settings', exact: true }).click();
  await page.getByRole('tab', { name: 'Custom game', exact: true }).click();
  await report().getByRole('heading', { name: 'Custom game' }).waitFor();
  assert.equal(await report().locator('body').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(20, 30, 40)');
  assert.equal(await report().locator('canvas').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(30, 80, 40)');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-workspace-theme', 'light');
  assert.deepEqual(errors, []);
  await context.close();
  await service.close();
  service = await createService({ repo, uiDir: path.join(root, 'dist') });
  const restarted = await browser.newPage();
  await restarted.goto(service.urls.workspace);
  await expect(restarted.locator('html')).toHaveAttribute('data-workspace-theme', 'light');
  console.log('Theme UI passed: saved choice, multi-window sync, system mode, Markdown/editing, live report updates without lost state, preserved artwork and dark Chats.');
} finally { await browser?.close(); await service?.close(); }
